sudo: required

language: scala

scala:
  - 2.11.8

jdk:
  - oraclejdk8

env:
  -  BUILD_PRJS=( hadoop-worker collector schemamanager )

script: for PRJ in "${BUILD_PRJS[@]}"; do cd $PRJ && mvn clean verify && cd .. ; done
