sudo: required

language: scala

scala:
  - 2.11.8

jdk:
  - oraclejdk8

env:
  -  BUILD_PRJ=hadoop-worker
  -  BUILD_PRJ=collector
  -  BUILD_PRJ=schemamanager

script: cd $BUILD_PRJ && mvn clean verify
